### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Review by chrzyki — APPROVED** [review]

**Comment by LinguList** [comment]
I guess, the only question we have here is if we list the papers additionally, or if we generate it from publications. If you think, the latter, @xrotwang, I'll delete this line. But if you're fine with the table, I think this is also easy to update in the future.

**Comment by tresoldi** [comment]
Just the order sounds a bit strange. Cormac is at the bottom, but other people who are not involved anymore are listed in chronological order. I'd either move him above @chrzyki or list all of those who are not involved, always in chronological order, after the active ones.

**Review by tresoldi — APPROVED** [review]

**Comment by LinguList** [comment]
yep, this was not following the logic, I also ordered the contributors alphabetically now.

**Comment by LinguList** [comment]
The order of contributors now follows the chronological principle, listing the contributors who are still active before the past ones, in alphabetical order, if there are more.

**Comment by LinguList** [comment]
I just merged, so if the list of papers is not needed, it can be easily removed.

**Pull request merged**
